#pragma once
//
// File: leg_conv.cpp
//
// MATLAB Coder version            : 23.2
// C/C++ source code generated on  : 30-Mar-2024 23:04:53
//

// Include Files
#include <cmath>
namespace app::controller {
//  Function Definitions
//
//  LEG_CONV
//      T = LEG_CONV(F,Tp,PHI1,PHI4)
//
//      T2    T1
//    _ _ ______
//    4* /    1*\
//       \      /
//        \    /
//
//  Arguments    : double F    推力
//                 double Tp   扭矩
//                 double phi1 电机角度
//                 double phi4 电机角度
//                 double T[2] 电机输出扭矩
//  Return Type  : void
//
void leg_conv(double F, double Tp, double phi1, double phi4, double T[2]) {
    double t2;
    double t20;
    double t21;
    double t23;
    double t26;
    double t3;
    double t4;
    double t41;
    double t5;
    double t6;
    double t7;
    double t8;
    //     This function was generated by the Symbolic Math Toolbox version 23.2.
    //     2024-07-15 23:13:02
    t2  = std::cos(phi1);
    t3  = std::cos(phi4);
    t4  = std::sin(phi1);
    t5  = std::sin(phi4);
    t6  = t2 * 0.148;
    t7  = t3 * 0.148;
    t8  = t4 * 0.148;
    t20 = t8 - t5 * 0.148;
    t23 = (t7 - t6) + 0.14;
    t21 = t20 * t20;
    t23 *= t23;
    t26 = t21 + t23;
    t21 = std::atan(
              1.0 / (((t3 * 0.07844 - t2 * 0.07844) + t26) + 0.0742)
              * ((t5 * 0.07844 - t4 * 0.07844)
                 + std::sqrt((t21 * 0.2809 + t23 * 0.2809) - t26 * t26)))
        * 2.0;
    t26  = std::cos(t21) * 0.265;
    t2   = std::sin(t21) * 0.265;
    t41  = std::sin(phi1 - t21);
    t23  = t8 + t2;
    t3   = (t6 + t26) - 0.07;
    t4   = std::atan2(t23, t3);
    t5   = 1.0 / std::sqrt(t23 * t23 + t3 * t3);
    t23  = std::atan((t20 + t2) * (1.0 / (((t6 - t7) + t26) - 0.14)));
    t2   = t21 - t4;
    t3   = -t4 + t23;
    t26  = std::sin(phi4 - t23);
    t23  = 1.0 / std::sin(-t21 + t23);
    T[0] = F * t41 * t23 * std::sin(t3) * -0.148 + Tp * t41 * t5 * t23 * std::cos(t3) * 0.148;
    T[1] = F * t26 * t23 * std::sin(t2) * 0.148 - Tp * t5 * t26 * t23 * std::cos(t2) * 0.148;
}

//
// File trailer for leg_conv.cpp
//
// [EOF]
//
} // namespace app