#pragma once
//
// File: leg_conv.cpp
//
// MATLAB Coder version            : 23.2
// C/C++ source code generated on  : 30-Mar-2024 23:04:53
//

// Include Files
#include <cmath>
namespace app::controller {
//  Function Definitions
//
//  LEG_CONV
//      T = LEG_CONV(F,Tp,PHI1,PHI4)
//
//      T2    T1
//    _ _ ______
//    4* /    1*\
//       \      /
//        \    /
//
//  Arguments    : double F    推力
//                 double Tp   扭矩
//                 double phi1 电机角度
//                 double phi4 电机角度
//                 double T[2] 电机输出扭矩
//  Return Type  : void
//
// 新腿
void leg_conv(double F, double Tp, double phi1, double phi4, double T[2]) {
    double t2;
    double t21;
    double t22;
    double t23;
    double t3;
    double t36;
    double t38;
    double t4;
    double t41;
    double t5;
    double t7;
    double t8;
    double t9;
    //     This function was generated by the Symbolic Math Toolbox version 23.2.
    //     2025-02-28 07:24:21
    t2  = std::cos(phi1);
    t3  = std::cos(phi4);
    t4  = std::sin(phi1);
    t5  = std::sin(phi4);
    t7  = t2 * 0.1525;
    t8  = t5 * 0.11;
    t9  = t4 * 0.1525;
    t38 = t8 - t9;
    t21 = t38 * t38;
    t22 = (t3 * 0.11 - t7) + 0.17;
    t23 = t22 * t22;
    t38 = (t21 + t23) - 0.0369;
    t36 =
        std::atan(
            1.0 / ((((t3 * 0.0352 - t2 * 0.0488) + t21) + t23) + 0.0175)
            * ((t5 * 0.0352 - t4 * 0.0488) + std::sqrt((t21 * 0.1024 + t23 * 0.1024) - t38 * t38)))
        * 2.0;
    t38  = std::cos(t36);
    t2   = std::sin(t36);
    t41  = std::sin(phi1 - t36);
    t5   = t9 + t2 * 0.26;
    t3   = (t7 + t38 * 0.26) - 0.085;
    t23  = std::atan2(t5, (t4 * 0.0 + t2 * 0.0) + t3);
    t21  = std::atan(((t9 - t8) + t2 * 0.16) * (-1.0 / (t22 - t38 * 0.16)));
    t5   = 1.0 / std::sqrt(t5 * t5 + t3 * t3);
    t38  = t36 - t23;
    t2   = -t23 + t21;
    t3   = std::sin(phi4 - t21);
    t21  = 1.0 / std::sin(-t36 + t21);
    T[0] = F * t41 * t21 * std::sin(t2) * -0.1525 + Tp * t41 * t5 * t21 * std::cos(t2) * 0.1525;
    T[1] = F * t3 * t21 * std::sin(t38) * 0.11 - Tp * t5 * t3 * t21 * std::cos(t38) * 0.11;
}

//
// File trailer for leg_conv.cpp
//
// [EOF]
//
} // namespace app